version: '3'

services:
  bot:
    build: .
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - SPREADSHEET_ID=${SPREADSHEET_ID}
      - USERS_SHEET_NAME=${USERS_SHEET_NAME:-Users}
      - RATINGS_SHEET_NAME=${RATINGS_SHEET_NAME:-Ratings}
      - SYNC_INTERVAL=${SYNC_INTERVAL:-300}
      - FAQ_UPDATE_INTERVAL=${FAQ_UPDATE_INTERVAL:-300}
      - DB_FILE=/app/data/bot_data.db
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"